# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'evaluateteams.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EvaluateTeams(object):
    def setupUi(self, EvaluateTeams):
        EvaluateTeams.setObjectName("EvaluateTeams")
        EvaluateTeams.resize(485, 535)
        self.gridLayout = QtWidgets.QGridLayout(EvaluateTeams)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_7 = QtWidgets.QLabel(EvaluateTeams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setMidLineWidth(-8)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cmbTeam = QtWidgets.QComboBox(EvaluateTeams)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cmbTeam.setFont(font)
        self.cmbTeam.setObjectName("cmbTeam")
        self.horizontalLayout_2.addWidget(self.cmbTeam)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.cmbMatch = QtWidgets.QComboBox(EvaluateTeams)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cmbMatch.setFont(font)
        self.cmbMatch.setObjectName("cmbMatch")
        self.horizontalLayout_2.addWidget(self.cmbMatch)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(EvaluateTeams)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 10, -1, 20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(EvaluateTeams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.lstPlayers = QtWidgets.QListWidget(EvaluateTeams)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lstPlayers.setFont(font)
        self.lstPlayers.setObjectName("lstPlayers")
        self.verticalLayout.addWidget(self.lstPlayers)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(EvaluateTeams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.lblTotPoints = QtWidgets.QLabel(EvaluateTeams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTotPoints.sizePolicy().hasHeightForWidth())
        self.lblTotPoints.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblTotPoints.setFont(font)
        self.lblTotPoints.setStyleSheet("color: rgb(0, 170, 127);")
        self.lblTotPoints.setObjectName("lblTotPoints")
        self.horizontalLayout.addWidget(self.lblTotPoints)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.lstPoints = QtWidgets.QListWidget(EvaluateTeams)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lstPoints.setFont(font)
        self.lstPoints.setObjectName("lstPoints")
        self.verticalLayout_2.addWidget(self.lstPoints)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.btnCalc = QtWidgets.QPushButton(EvaluateTeams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCalc.sizePolicy().hasHeightForWidth())
        self.btnCalc.setSizePolicy(sizePolicy)
        self.btnCalc.setMinimumSize(QtCore.QSize(150, 0))
        self.btnCalc.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCalc.setFont(font)
        self.btnCalc.setObjectName("btnCalc")
        self.horizontalLayout_4.addWidget(self.btnCalc)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)

        self.retranslateUi(EvaluateTeams)
        QtCore.QMetaObject.connectSlotsByName(EvaluateTeams)

    def retranslateUi(self, EvaluateTeams):
        _translate = QtCore.QCoreApplication.translate
        EvaluateTeams.setWindowTitle(_translate("EvaluateTeams", "Evaluate Teams"))
        self.label_7.setText(_translate("EvaluateTeams", "Evaluate the Performance of your Fantasy Team"))
        self.label_6.setText(_translate("EvaluateTeams", "Players"))
        self.label_5.setText(_translate("EvaluateTeams", "Points"))
        self.lblTotPoints.setText(_translate("EvaluateTeams", "##"))
        self.btnCalc.setText(_translate("EvaluateTeams", "Calculate Score"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EvaluateTeams = QtWidgets.QDialog()
    ui = Ui_EvaluateTeams()
    ui.setupUi(EvaluateTeams)
    EvaluateTeams.show()
    sys.exit(app.exec_())

